
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/09a_bagoftricks.ipynb

from exp.nb_09 import *

def prev_pow_2(x): 2**math.floor(math.log2(x))

def get_cnn_layers(data, nfs, layer, **kwargs):
    pass