
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/08a_lsuv.ipynb

from exp.nb_08 import *

def get_batch(dl, run):
    run.xb, run.yb = next(iter(dl))
    for cb in run.cbs: cb.set_runner(run)
    run('begin_batch')
    return run.xb, run.yb

def find_mods(m, func):
    if func(m): return [m]
    return sum([find_mods(o, func) for o in m.children()], [])

def is_lin_layer(l):
    layers = (nn.Conv1d, nn.Conv2d, nn.Conv3d, nn.Linear, nn.ReLU)
    return isinstance(l, layers)